### ISSUE TITLE
the library is fail to be installed at Ubuntu 18.04.3 

### ISSUE THREAD

**Issue by jefflutmo** [clintval/seattle-food-truck#15]
Hi, 

when I try to install the library, I got the failure as following:

ubuntu@ip-172-31-21-75:~$ pip install seattle-food-truck
Collecting seattle-food-truck
  Downloading https://files.pythonhosted.org/packages/c7/c7/9f404dd5d008aaaa8d6af06b927ec3a6f6818e70cc62f6037a1bd4524d78/seattle_food_truck-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-d4bM21/seattle-food-truck/setup.py", line 11
        ARTIFACT = f'https://github.com/{AUTHOR}/{PACKAGE}/archive/v{VERSION}.tar.gz'
                                                                                    ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d4bM21/seattle-food-truck/
ubuntu@ip-172-31-21-75:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
ubuntu@ip-172-31-21-75:~$ 

any solution? 

thanks,

**Comment by clintval** [comment]
This library requires Py3.6+. I will make a note in the README
